### ISSUE TITLE
Sharing iP code quality feedback [for @zaidansani]

### ISSUE THREAD

**Issue by nus-se-script** [zaidansani/ip#4]
@zaidansani We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, to help you improve the iP code further.

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most three example are given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Naming boolean variables/methods

Example from [`src/main/java/zaibot/utils/Storage.java` lines `55-55`](https://github.com/zaidansani/ip/blob/a645c9876f04ee5773d4884e08f9c1bea3f40761/src/main/java/zaibot/utils/Storage.java#L55..L55):

```java

            boolean first = true;

``` 

**Suggestion:** Follow the given naming convention for boolean variables/methods (e.g., use a boolean-sounding prefix).You may ignore the above if you think the name already follows the convention (the script can report false positives in some cases)

### Aspect: Brace Style

No easy-to-detect issues :+1: 

### Aspect: Package Name Style

No easy-to-detect issues :+1: 

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

No easy-to-detect issues :+1: 

### Aspect: Method Length

No easy-to-detect issues :+1: 

### Aspect: Class size

No easy-to-detect issues :+1: 

### Aspect: Header Comments

Example from [`src/main/java/zaibot/utils/TaskList.java` lines `108-114`](https://github.com/zaidansani/ip/blob/a645c9876f04ee5773d4884e08f9c1bea3f40761/src/main/java/zaibot/utils/TaskList.java#L108..L114):

```java

    /**
     * Unmark the task in the task list based on the number.
     * Note that the number begins from one, unlike an index.
     *
     * @param number A number, starting from 1
     * @return The task
     */

``` 

**Suggestion:** Ensure method/class header comments follow the format specified in the coding standard, in particular, the phrasing of the overview statement.

### Aspect: Recent Git Commit Message

No easy-to-detect issues :+1: 

### Aspect: Binary files in repo

No easy-to-detect issues :+1: 

----

:information_source: The bot account used to post this issue is un-manned. **Do not reply to this post** (as those replies will not be read). Instead, contact `cs2103@comp.nus.edu.sg` if you want to follow up on this post.

**Comment by zaidansani** [comment]
Issues fixed.
